//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.ServiceReference1 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.Service1Soap")]
    public interface Service1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/suma", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int suma(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/suma", ReplyAction="*")]
        System.Threading.Tasks.Task<int> sumaAsync(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/persona", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet persona();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/persona", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> personaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/personaUniq", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet personaUniq(int ci);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/personaUniq", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> personaUniqAsync(int ci);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/personaDel", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet personaDel(int ci);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/personaDel", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> personaDelAsync(int ci);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/personaCrea", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet personaCrea(int ci, string nombreCompleto, string fechaDeNacimiento, string departamento, string telefono);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/personaCrea", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> personaCreaAsync(int ci, string nombreCompleto, string fechaDeNacimiento, string departamento, string telefono);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/personaEdit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet personaEdit(int ci, string nombreCompleto, string fechaDeNacimiento, string departamento, string telefono);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/personaEdit", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> personaEditAsync(int ci, string nombreCompleto, string fechaDeNacimiento, string departamento, string telefono);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : WindowsFormsApplication1.ServiceReference1.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<WindowsFormsApplication1.ServiceReference1.Service1Soap>, WindowsFormsApplication1.ServiceReference1.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync() {
            return base.Channel.HelloWorldAsync();
        }
        
        public int suma(int a, int b) {
            return base.Channel.suma(a, b);
        }
        
        public System.Threading.Tasks.Task<int> sumaAsync(int a, int b) {
            return base.Channel.sumaAsync(a, b);
        }
        
        public System.Data.DataSet persona() {
            return base.Channel.persona();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> personaAsync() {
            return base.Channel.personaAsync();
        }
        
        public System.Data.DataSet personaUniq(int ci) {
            return base.Channel.personaUniq(ci);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> personaUniqAsync(int ci) {
            return base.Channel.personaUniqAsync(ci);
        }
        
        public System.Data.DataSet personaDel(int ci) {
            return base.Channel.personaDel(ci);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> personaDelAsync(int ci) {
            return base.Channel.personaDelAsync(ci);
        }
        
        public System.Data.DataSet personaCrea(int ci, string nombreCompleto, string fechaDeNacimiento, string departamento, string telefono) {
            return base.Channel.personaCrea(ci, nombreCompleto, fechaDeNacimiento, departamento, telefono);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> personaCreaAsync(int ci, string nombreCompleto, string fechaDeNacimiento, string departamento, string telefono) {
            return base.Channel.personaCreaAsync(ci, nombreCompleto, fechaDeNacimiento, departamento, telefono);
        }
        
        public System.Data.DataSet personaEdit(int ci, string nombreCompleto, string fechaDeNacimiento, string departamento, string telefono) {
            return base.Channel.personaEdit(ci, nombreCompleto, fechaDeNacimiento, departamento, telefono);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> personaEditAsync(int ci, string nombreCompleto, string fechaDeNacimiento, string departamento, string telefono) {
            return base.Channel.personaEditAsync(ci, nombreCompleto, fechaDeNacimiento, departamento, telefono);
        }
    }
}
